name: Application Name
log_settings:
  level: info
  dir_path: logs
  max_size: 10 KB
  file_name: main
  msg_format: '{level} | {date} | {msg}'
  date_format: '%Y-%m-%d %H:%M:%S'
commands:
  - cid: add-web-tool
    module: main
    menu: test
    arguments:
      name: Default Name