name: core
version: 1.0.5
description: This is a core module
services:
  - id: configService
    class: CoreConfigService
    args: ['appConfigs']
  - id: logService
    class: CoreLogService
    args: ['@configService']
  - id: argService
    class: CoreArgService
    args: ['@configService']
  - id: fieldService
    class: CoreFieldService
    args: ['@configService', '@argService']
  - id: cmdService
    class: CoreCmdService
    args: ['@fieldService', '@argService']
