name: core
version: 1.0.5
description: This is a core module
services:
  - id: configService
    class: CoreConfigService
    args: ['appConfigs']
  - id: logService
    class: CoreLogService
    args: ['appConfigs']
  - id: argService
    class: CoreArgService
    args: ['@configService']
