application:
  name: 'Main Application'
  modes:
    - id: cmd
      module: core
      runner: CoreCmdExecApp
    - id: init
      module: core
      runner: CoreInitExecApp
log_settings:
  level: error
  dir_path: logs
  max_size: 10 KB
  msg_format: '{level} | {date} | {msg}'
  date_format: '%Y-%m-%d %H:%M:%S'
